// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Announce represents a row from 'public.announce'.
type Announce struct {
	Room    string    `json:"room" db:"room"`       // room
	Text    string    `json:"text" db:"text"`       // text
	Marquee bool      `json:"marquee" db:"marquee"` // marquee
	Period  NullInt64 `json:"period" db:"period"`   // period

	// xo fields
	_exists, _deleted bool
}
