// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// ChatType is the 'chat_type' enum type from schema 'public'.
type ChatType uint16

const (
	// ChatTypePoster is the 'poster' ChatType.
	ChatTypePoster = ChatType(1)

	// ChatTypePeople is the 'people' ChatType.
	ChatTypePeople = ChatType(2)
)
