// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// CommentToPoster represents a row from 'public.comment_to_poster'.
type CommentToPoster struct {
	Comment string `json:"comment" db:"comment"` // comment
	Poster  string `json:"poster" db:"poster"`   // poster

	// xo fields
	_exists, _deleted bool
}
