// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Comment represents a row from 'public.comment'.
type Comment struct {
	ID          string     `json:"id" db:"id"`                     // id
	Timestamp   int64      `json:"timestamp" db:"timestamp"`       // timestamp
	LastUpdated int64      `json:"last_updated" db:"last_updated"` // last_updated
	Person      string     `json:"person" db:"person"`             // person
	Text        string     `json:"text" db:"text"`                 // text
	Room        NullString `json:"room" db:"room"`                 // room
	X           NullInt64  `json:"x" db:"x"`                       // x
	Y           NullInt64  `json:"y" db:"y"`                       // y
	Kind        NullString `json:"kind" db:"kind"`                 // kind
	ReplyTo     NullString `json:"reply_to" db:"reply_to"`         // reply_to

	// xo fields
	_exists, _deleted bool
}
