// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// MapCell represents a row from 'public.map_cell'.
type MapCell struct {
	ID           string      `json:"id" db:"id"`                                 // id
	Room         string      `json:"room" db:"room"`                             // room
	X            int         `json:"x" db:"x"`                                   // x
	Y            int         `json:"y" db:"y"`                                   // y
	Kind         string      `json:"kind" db:"kind"`                             // kind
	PosterNumber *NullInt64  `json:"poster_number,omitempty" db:"poster_number"` // poster_number
	CustomImage  *NullString `json:"custom_image,omitempty" db:"custom_image"`   // custom_image

	// xo fields
	_exists, _deleted bool
}
