// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// PersonInChatGroup represents a row from 'public.person_in_chat_group'.
type PersonInChatGroup struct {
	Person string `json:"person" db:"person"` // person
	Chat   string `json:"chat" db:"chat"`     // chat

	// xo fields
	_exists, _deleted bool
}
