// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// PersonRoomAccess represents a row from 'public.person_room_access'.
type PersonRoomAccess struct {
	Room   string   `json:"room" db:"room"`     // room
	Person string   `json:"person" db:"person"` // person
	Role   UserRole `json:"role" db:"role"`     // role

	// xo fields
	_exists, _deleted bool
}
