// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// PersonPosition represents a row from 'public.person_position'.
type PersonPosition struct {
	Person      string    `json:"person" db:"person"`             // person
	LastUpdated int64     `json:"last_updated" db:"last_updated"` // last_updated
	Direction   Direction `json:"direction" db:"direction"`       // direction
	Room        string    `json:"room" db:"room"`                 // room
	X           int       `json:"x" db:"x"`                       // x
	Y           int       `json:"y" db:"y"`                       // y

	// xo fields
	_exists, _deleted bool
}
