// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Poster represents a row from 'public.poster'.
type Poster struct {
	ID               string     `json:"id" db:"id"`                                 // id
	LastUpdated      int64      `json:"last_updated" db:"last_updated"`             // last_updated
	Location         string     `json:"location" db:"location"`                     // location
	Title            NullString `json:"title" db:"title"`                           // title
	Author           string     `json:"author" db:"author"`                         // author
	AccessLog        bool       `json:"access_log" db:"access_log"`                 // access_log
	AuthorOnlineOnly bool       `json:"author_online_only" db:"author_online_only"` // author_online_only

	// xo fields
	_exists, _deleted bool
}
