// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// PosterViewer represents a row from 'public.poster_viewer'.
type PosterViewer struct {
	Poster     string    `json:"poster" db:"poster"`           // poster
	Person     string    `json:"person" db:"person"`           // person
	JoinedTime int64     `json:"joined_time" db:"joined_time"` // joined_time
	LeftTime   NullInt64 `json:"left_time" db:"left_time"`     // left_time
	LastActive NullInt64 `json:"last_active" db:"last_active"` // last_active
}
