// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Room represents a row from 'public.room'.
type Room struct {
	ID                  string `json:"id" db:"id"`     // id
	Name                string `json:"name" db:"name"` // name
	PosterLocationCount int64  `json:"poster_location_count"`
	PosterCount         int64  `json:"poster_count"`
	NumCols             int64  `json:"numCols"`
	NumRows             int64  `json:"numRows"`
	// xo fields
	_exists, _deleted bool
}

// RoomByID retrieves a row from 'public.room' as a Room.
//
// Generated from index 'room_pkey'.
func RoomByID(db XODB, id string) (*Room, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, name ` +
		`FROM public.room ` +
		`WHERE id = $1`

	// run query
	XOLog(sqlstr, id)
	r := Room{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&r.ID, &r.Name)
	if err != nil {
		return nil, err
	}

	return &r, nil
}
