// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"errors"
)

// UserRole is the 'user_role' enum type from schema 'public'.
type UserRole uint16

const (
	// UserRoleUser is the 'user' UserRole.
	UserRoleUser = UserRole(1)

	// UserRoleAdmin is the 'admin' UserRole.
	UserRoleAdmin = UserRole(2)
)

// String returns the string value of the UserRole.
func (ur UserRole) String() string {
	var enumVal string

	switch ur {
	case UserRoleUser:
		enumVal = "user"

	case UserRoleAdmin:
		enumVal = "admin"
	}

	return enumVal
}

// MarshalText marshals UserRole into text.
func (ur UserRole) MarshalText() ([]byte, error) {
	return []byte(ur.String()), nil
}

// UnmarshalText unmarshals UserRole from text.
func (ur *UserRole) UnmarshalText(text []byte) error {
	switch string(text) {
	case "user":
		*ur = UserRoleUser

	case "admin":
		*ur = UserRoleAdmin

	default:
		return errors.New("invalid UserRole")
	}

	return nil
}

// Value satisfies the sql/driver.Valuer interface for UserRole.
func (ur UserRole) Value() (driver.Value, error) {
	return ur.String(), nil
}

// Scan satisfies the database/sql.Scanner interface for UserRole.
func (ur *UserRole) Scan(src interface{}) error {
	buf, ok := src.([]byte)
	if !ok {
		return errors.New("invalid UserRole")
	}

	return ur.UnmarshalText(buf)
}
